# Generated by Django 3.1.2 on 2021-03-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squares', '0002_squarescsv_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squarescsv',
            name='name',
        ),
        migrations.AlterField(
            model_name='squarescsv',
            name='file',
            field=models.FileField(upload_to='csv_files', verbose_name='squares'),
        ),
    ]
