# Generated by Django 3.1.2 on 2021-03-29 19:53

import Squares.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squares', '0003_auto_20210329_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squarescsv',
            name='file',
            field=models.FileField(upload_to=Squares.models.name_change),
        ),
    ]
