# Generated by Django 3.1.2 on 2021-04-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squares', '0004_auto_20210329_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinningLosingNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winning_numbers', models.IntegerField()),
                ('losing_numbers', models.IntegerField()),
            ],
        ),
    ]
