# Generated by Django 3.1.2 on 2021-04-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squares', '0005_winninglosingnumbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='LosingNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot1', models.IntegerField(max_length=1)),
                ('spot2', models.IntegerField(max_length=1)),
                ('spot3', models.IntegerField(max_length=1)),
                ('spot4', models.IntegerField(max_length=1)),
                ('spot5', models.IntegerField(max_length=1)),
                ('spot6', models.IntegerField(max_length=1)),
                ('spot7', models.IntegerField(max_length=1)),
                ('spot8', models.IntegerField(max_length=1)),
                ('spot9', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='WinningNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot1', models.IntegerField(max_length=1)),
                ('spot2', models.IntegerField(max_length=1)),
                ('spot3', models.IntegerField(max_length=1)),
                ('spot4', models.IntegerField(max_length=1)),
                ('spot5', models.IntegerField(max_length=1)),
                ('spot6', models.IntegerField(max_length=1)),
                ('spot7', models.IntegerField(max_length=1)),
                ('spot8', models.IntegerField(max_length=1)),
                ('spot9', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='WinningLosingNumbers',
        ),
    ]
