# Generated by Django 3.1.2 on 2021-04-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squares', '0006_auto_20210401_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='losingnumbers',
            name='spot10',
            field=models.IntegerField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='winningnumbers',
            name='spot10',
            field=models.IntegerField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
