# Generated by Django 3.1.2 on 2021-04-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squares', '0007_auto_20210401_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='losingnumbers',
            name='spot1',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='losingnumbers',
            name='spot10',
            field=models.IntegerField(default=9, max_length=1),
        ),
        migrations.AlterField(
            model_name='losingnumbers',
            name='spot2',
            field=models.IntegerField(default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='losingnumbers',
            name='spot3',
            field=models.IntegerField(default=2, max_length=1),
        ),
        migrations.AlterField(
            model_name='losingnumbers',
            name='spot4',
            field=models.IntegerField(default=3, max_length=1),
        ),
        migrations.AlterField(
            model_name='losingnumbers',
            name='spot5',
            field=models.IntegerField(default=4, max_length=1),
        ),
        migrations.AlterField(
            model_name='losingnumbers',
            name='spot6',
            field=models.IntegerField(default=5, max_length=1),
        ),
        migrations.AlterField(
            model_name='losingnumbers',
            name='spot7',
            field=models.IntegerField(default=6, max_length=1),
        ),
        migrations.AlterField(
            model_name='losingnumbers',
            name='spot8',
            field=models.IntegerField(default=7, max_length=1),
        ),
        migrations.AlterField(
            model_name='losingnumbers',
            name='spot9',
            field=models.IntegerField(default=8, max_length=1),
        ),
        migrations.AlterField(
            model_name='winningnumbers',
            name='spot1',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='winningnumbers',
            name='spot10',
            field=models.IntegerField(default=9, max_length=1),
        ),
        migrations.AlterField(
            model_name='winningnumbers',
            name='spot2',
            field=models.IntegerField(default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='winningnumbers',
            name='spot3',
            field=models.IntegerField(default=2, max_length=1),
        ),
        migrations.AlterField(
            model_name='winningnumbers',
            name='spot4',
            field=models.IntegerField(default=3, max_length=1),
        ),
        migrations.AlterField(
            model_name='winningnumbers',
            name='spot5',
            field=models.IntegerField(default=4, max_length=1),
        ),
        migrations.AlterField(
            model_name='winningnumbers',
            name='spot6',
            field=models.IntegerField(default=5, max_length=1),
        ),
        migrations.AlterField(
            model_name='winningnumbers',
            name='spot7',
            field=models.IntegerField(default=6, max_length=1),
        ),
        migrations.AlterField(
            model_name='winningnumbers',
            name='spot8',
            field=models.IntegerField(default=7, max_length=1),
        ),
        migrations.AlterField(
            model_name='winningnumbers',
            name='spot9',
            field=models.IntegerField(default=8, max_length=1),
        ),
    ]
