# Generated by Django 3.1.2 on 2021-04-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squares', '0009_auto_20210401_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=2)),
                ('first_round', models.IntegerField(default=0)),
                ('second_round', models.IntegerField(default=0)),
                ('sweet_sixteen', models.IntegerField(default=0)),
                ('elite_eight', models.IntegerField(default=0)),
                ('final_four', models.IntegerField(default=0)),
                ('championship', models.IntegerField(default=0)),
            ],
        ),
    ]
