# Generated by Django 3.1.2 on 2021-04-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Squares', '0010_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundAmounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_round', models.FloatField(default=0)),
                ('second_round', models.FloatField(default=0)),
                ('sweet_sixteen', models.FloatField(default=0)),
                ('elite_eight', models.FloatField(default=0)),
                ('final_four', models.FloatField(default=0)),
                ('championship', models.FloatField(default=0)),
            ],
        ),
    ]
